In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score, accuracy_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

Dataset

In this homework, we will use the 2026 lead-scoring dataset. Download it from here.

Or you can do it with wget:

In [2]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv

--2026-10-02 12:29:43--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 278746 (272K) [text/plain]
Saving to: ‘course_lead_scoring_2026.csv.3’

course_lead_scoring 100%[===================>] 272.21K  --.-KB/s    in 0.005s

2026-10-02 12:29:43 (48.5 MB/s) - ‘course_lead_scoring_2026.csv.3’ saved [278746/278746]

Data preparation

Check if the missing values are presented in the features.
If there are missing values:
For categorical features, replace them with 'NA'
For numerical features, replace with with 0.0

In [3]:
df = pd.read_csv('course_lead_scoring_2026.csv')
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [4]:
df.head().T

,0,1,2,3,4
lead_source,organic_search,social_media,referral,paid_ads,referral
industry,technology,technology,retail,manufacturing,manufacturing
employment_status,employed,employed,employed,student,student
location,europe,south_america,europe,NaN,north_america
annual_income,88160.0,72688.0,44697.0,NaN,24062.0
number_of_courses_viewed,3,3,3,3,4
interaction_count,4,7,4,6,5
lead_score,0.64,0.72,0.58,0.57,0.62
converted,1,1,1,0,1

In [5]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [6]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [7]:
df.lead_source = df.lead_source.fillna('NA')
df.industry = df.industry.fillna('NA')
df.employment_status  = df.employment_status.fillna('NA')
df.location = df.location.fillna('NA')
df.annual_income = df.annual_income.fillna(0.0)
df.lead_score = df.lead_score.fillna(0.0)

In [8]:
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [9]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

Question 1
What is the most frequent observation (mode) for the column industry?

In [10]:
df.industry.mode()

0    technology
Name: industry, dtype: str

The most frequent observation (mode) for the column industry, is 'technology'.

Question 2
Create the correlation matrix for the numerical features of your dataset. In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?

interaction_count and lead_score
number_of_courses_viewed and lead_score
number_of_courses_viewed and interaction_count
annual_income and interaction_count
Only consider the pairs above when answering this question.

In [11]:
numerical = [
    'annual_income',
    'number_of_courses_viewed',
    'interaction_count',
    'lead_score'
]

df_num = df[numerical]

In [12]:
df_num.corr()

,annual_income,number_of_courses_viewed,interaction_count,lead_score
annual_income,1.000000,0.161300,0.122842,0.229496
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204
interaction_count,0.122842,0.721609,1.000000,0.915746
lead_score,0.229496,0.757204,0.915746,1.000000

The two features that have the biggest correlation are 'interaction_count' and 'lead_score'.

Split the data
Make sure that the target value converted is not in your dataframe.

In [13]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

In [14]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [15]:
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train['converted']
del df_val['converted']
del df_test['converted']

In [16]:
df_train.shape, df_val.shape, df_test.shape

((3000, 8), (1000, 8), (1000, 8))

In [17]:
'converted' in df_train.columns

False

Question 3
Calculate the mutual information score between converted and other categorical variables in the dataset. Use the training set only.
Round the scores to 2 decimals using round(score, 2).
Which of these variables has the biggest mutual information score?

In [18]:
categorical = [
    'lead_source',
    'industry',
    'employment_status',
    'location'
]

In [19]:
from sklearn.metrics import mutual_info_score

In [20]:
def mutual_info_score_func(series):
    return mutual_info_score(series, y_train)

mi = df_train[categorical].apply(mutual_info_score_func)

mi.round(2).sort_values(ascending=False)

lead_source          0.03
employment_status    0.02
industry             0.00
location             0.00
dtype: float64

Variable 'lead_source' has the biggest mutual information score.

Question 4
Now let's train a logistic regression.
Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
Fit the model on the training dataset.
To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
Calculate the accuracy on the validation dataset and round it to 2 decimal digits.
What accuracy did you get?

In [21]:
dicts = df[categorical + numerical].to_dict(orient='records')

In [22]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [23]:
X_train.shape

(3000, 28)

In [24]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [25]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    solver='liblinear',
    C=1.0,
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [26]:
y_pred = model.predict_proba(X_val)[:, 1]

In [27]:
converted_decision = (y_pred >= 0.5)

In [28]:
(y_val == converted_decision).mean()

np.float64(0.645)

The accuracy we get is 0.645. If we round it to 2 decimal digits, it becomes 0.65.

Question 5
Let's find the least useful feature using the feature elimination technique.
Train a model using the same features and parameters as in Q4 (without rounding).
Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
For each feature, calculate the difference between the original accuracy and the accuracy without the feature.
Which of following feature has the smallest difference?

In [29]:
original_accuracy = 0.645

In [30]:
features_without_lead_source = [
    feature for feature in categorical + numerical
    if feature != 'lead_source'
]

In [31]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[features_without_lead_source].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [32]:
X_train.shape

(3000, 22)

In [33]:
val_dict = df_val[features_without_lead_source].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [34]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    solver='liblinear',
    C=1.0,
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [35]:
y_pred = model.predict_proba(X_val)[:, 1]

In [36]:
converted_decision = (y_pred >= 0.5)

In [37]:
accuracy_without_lead_source = (y_val == converted_decision).mean()

In [38]:
print (accuracy_without_lead_source)

0.642

In [39]:
difference_lead_source = original_accuracy - accuracy_without_lead_source
difference_lead_source

np.float64(0.0030000000000000027)

In [40]:
features_number_of_courses_viewed = [
    feature for feature in categorical + numerical
    if feature != 'number_of_courses_viewed'
]

In [41]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[features_number_of_courses_viewed].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [42]:
X_train.shape

(3000, 27)

In [43]:
val_dict = df_val[features_number_of_courses_viewed].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [44]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    solver='liblinear',
    C=1.0,
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [45]:
y_pred = model.predict_proba(X_val)[:, 1]

In [46]:
converted_decision = (y_pred >= 0.5)

In [47]:
accuracy_without_number_of_courses_viewed = (y_val == converted_decision).mean()

In [48]:
print (accuracy_without_number_of_courses_viewed)

0.643

In [49]:
difference_number_of_courses_viewed = original_accuracy - accuracy_without_number_of_courses_viewed
difference_number_of_courses_viewed

np.float64(0.0020000000000000018)

In [50]:
features_interaction_count = [
    feature for feature in categorical + numerical
    if feature != 'interaction_count'
]

In [51]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[features_interaction_count].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [52]:
X_train.shape

(3000, 27)

In [53]:
val_dict = df_val[features_interaction_count].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [54]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    solver='liblinear',
    C=1.0,
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [55]:
y_pred = model.predict_proba(X_val)[:, 1]

In [56]:
converted_decision = (y_pred >= 0.5)

In [57]:
accuracy_without_interaction_count = (y_val == converted_decision).mean()

In [58]:
print (accuracy_without_interaction_count)

0.601

In [60]:
difference_interaction_count = original_accuracy - accuracy_without_interaction_count
difference_interaction_count

np.float64(0.04400000000000004)

Feature 'number_of_courses_viewed' has the smallest difference = 0.002

Question 6
Now let's train a regularized logistic regression.
Let's try the following values of the parameter C: [0.000001, 0.00001, 0.0001, 0.001].
Train models using all the features as in Q4.
Calculate the accuracy on the validation dataset and round it to 3 decimal digits.
Which of these C leads to the best accuracy on the validation set?

In [61]:
features = categorical + numerical

dv = DictVectorizer(sparse=False)

train_dicts = df_train[features].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)

val_dicts = df_val[features].to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [62]:
C_values = [0.000001, 0.00001, 0.0001, 0.001]

In [64]:
results = []
for C in C_values:
    model = LogisticRegression(
    solver='liblinear',
    C = C,
    max_iter=1000,
    random_state=42)

    model.fit(X_train, y_train)

    y_pred = model.predict_proba(X_val)[:, 1]
    converted_decision = (y_pred >= 0.5)
    accuracy = (y_val == converted_decision).mean() 
    results.append((C, round(accuracy, 3)))

In [65]:
results

[(1e-06, np.float64(0.598)),
 (1e-05, np.float64(0.598)),
 (0.0001, np.float64(0.613)),
 (0.001, np.float64(0.645))]

For C = 0.001 we get the best accuracy on the validation set, 0.645.